version: "3"
services:
  multa-agent:
    container_name: multa-agent
    environment:
      - DEVICE_NAME=multa-agent-compose-armv7
      - DEVICE_SYNC_TIME=10
    image: 112646120612.dkr.ecr.us-east-1.amazonaws.com/multa-agent-armv7:0.0.2
    network_mode: host
    privileged: true
    restart: always
    volumes:
    - device-data:/device

volumes:
  device-data:

