version: "3"
services:
  multa-metrics-agent:
    container_name: multa-metrics-agent
    image: 112646120612.dkr.ecr.us-east-1.amazonaws.com/multa-agent-i386:0.0.3
    network_mode: host
    privileged: true
    restart: always
