import os

DEVICE_CONFIGURATION_URL = os.environ.get("DEVICE_CONFIGURATION_URL", "https://cvm-agent.dev.multa.io/multa-agent/")

DEVICE_SUCCESSFUL_REGISTRATION = os.environ.get("DEVICE_SUCCESSFUL_REGISTRATION", "0")
DEVICE_ALREADY_REGISTERED_ERROR = os.environ.get("DEVICE_ALREADY_REGISTERED_ERROR", "1")
DEVICE_REGISTRATION_PROCESS_ERROR = os.environ.get("DEVICE_REGISTRATION_PROCESS_ERROR", "2")
DEVICE_INVALID_DATA = os.environ.get("DEVICE_INVALID_DATA", "3")
DEVICE_REGISTRATION_UNKNOWN_ERROR = os.environ.get("DEVICE_REGISTRATION_UNKNOWN_ERROR", "127")
